### PR TITLE
Added spdx license detection, closes #8

### LINKED ISSUE #8: If license url is not found, it should link to spdx license url if it exists

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by niftylettuce** [comment]
@sindresorhus your work is being used here 🎉 thank you! 🙇

**Comment by wooorm** [comment]
👋

Thanks for the PR!

1. Your linking the author's name, not the SPDX
2. IANAL, but it's suggested to always include a license file in a project. I don't think we should support and make it easy to not do so.

**Comment by niftylettuce** [comment]
@wooorm this is just a back-up in case there isn't one, it will still link you, so I guess it protects user somewhat? 👍

**Comment by niftylettuce** [comment]
DOH 🤦‍♂️ Just realized what you mean - the AUTHOR's name not the URL, oh wow.

**Comment by niftylettuce** [comment]
@wooorm I pushed an update that fixed the issues

**Comment by wooorm** [comment]
This probably fails coverage because now there's no case where the SPDX is unknown!

**Comment by niftylettuce** [comment]
@wooorm any chance you could fix?  afk for next few days

**Comment by wooorm** [comment]
You could change an MIT license to MITX or something? 🤷‍♂️

**Comment by niftylettuce** [comment]
@wooorm Done!  Accept + release new version? Thank you

**Comment by wooorm** [comment]
I don’t release major versions lightly. It depends on GH-7. Maybe in a few days, when that’s done?

**Comment by wooorm** [comment]
Oh, I forgot: This looks great otherwise! Thank you!

**Comment by niftylettuce** [comment]
Sorry I don't have the time right now to make a bunch of different PR's, I don't see why we can't merge in the commits above as-is, they're clean.

**Comment by wooorm** [comment]
Thank you! I changed the code a bit so it was hard to merge this, also because it’s one big PR. I did use your patches as inspiration though.

**Pull request closed without merging**
